import {
  Oswald,
  Manrope,
} from "next/font/google";

import type { Metadata } from "next";
import "./globals.css";
import MainHeader from "@/components/main-header";

export const oswald = Oswald({
  subsets: ["latin"],
  weight: ["200", "400", "700"],
});

export const manrope = Manrope({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manrope.className} ${manrope.className} h-full antialiased`}
    >
      <body className="min-h-full bg-[#CCAEA4] py-8 px-8">
        <div className="max-w-7xl mx-auto">
          <div className="w-full">
            <MainHeader></MainHeader>
            <section className="bg-white px-10">
              {children}    
            </section>
          </div>
        </div>
      </body>
    </html>
  );
}
